### PR TITLE
Inject scripts before page scripts run

### PR DESCRIPTION
**Pull request by tejohnso**
See https://stackoverflow.com/questions/26832848/chrome-apps-webview-tag-how-to-inject-css-or-js-in-time

https://trello.com/c/o8dMjtWz

### CODE REVIEW

**Comment by andrecardoso** [comment]
@tejohnso I switched to this branch to test it, but I'm having some errors like `TypeError: Cannot read property 'postMessage' of null` when it tries to send messages to viewer. Is it working fine there?

**Comment by tejohnso** [comment]
All fine on my end. I'll try a different set up.

**Comment by andrecardoso** [comment]
[(5) Defect 162: Rise Player not using RLS](https://trello.com/c/o8dMjtWz/4771-5-defect-162-rise-player-not-using-rls)

**Comment by andrecardoso** [comment]
[(5) Defect 162: Rise Player not using RLS](https://trello.com/c/o8dMjtWz/4771-5-defect-162-rise-player-not-using-rls)

**Pull request merged**
