### PR TITLE
Set up babel

### PR DESCRIPTION
**Pull request by andrecardoso**

### CODE REVIEW

**Comment by rudibravo** [comment]
@andrecardoso do you want to push this change on todays rollout? Thanks

**Comment by andrecardoso** [comment]
[(2) ChrOS: Set minimum version and setup babel](https://trello.com/c/Bs5BqBSO/4650-2-chros-set-minimum-version-and-setup-babel)

**Comment by andrecardoso** [comment]
@rudibravo this is not included in today's rollout, if we see that there's errors related to unsupported js methods we can include it as part of next rollout increase

**Comment by andrecardoso** [comment]
@tejohnso agreed. Do you have any idea about how can we test this? Maybe install Chrome 42 in some VM and test the app as extension?

**Comment by tejohnso** [comment]
I'll test it with browserling

**Pull request merged**
